//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog
    {
        public int ActionLogId { get; set; }
        public string UserEmail { get; set; }
        public string Action { get; set; }
        public System.DateTime LogDate { get; set; }
        public Nullable<bool> ISGranted { get; set; }
        public System.DateTime DateStamp { get; set; }
    }
}
