//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ADitEntities : DbContext
    {
        public ADitEntities()
            : base("name=ADitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionLog> ActionLogs { get; set; }
        public virtual DbSet<ApconApprovalType> ApconApprovalTypes { get; set; }
        public virtual DbSet<ApconApprovalTypePrice> ApconApprovalTypePrices { get; set; }
        public virtual DbSet<AppActivityLog> AppActivityLogs { get; set; }
        public virtual DbSet<AppRole> AppRoles { get; set; }
        public virtual DbSet<ArtWorkPrice> ArtWorkPrices { get; set; }
        public virtual DbSet<BrandingDesignElement> BrandingDesignElements { get; set; }
        public virtual DbSet<BrandingDesignElementPrice> BrandingDesignElementPrices { get; set; }
        public virtual DbSet<BrandingMaterial> BrandingMaterials { get; set; }
        public virtual DbSet<BrandingMaterialPrice> BrandingMaterialPrices { get; set; }
        public virtual DbSet<BrandingTransaction> BrandingTransactions { get; set; }
        public virtual DbSet<BrandingTransactionAttachment> BrandingTransactionAttachments { get; set; }
        public virtual DbSet<BrandingTransactionColor> BrandingTransactionColors { get; set; }
        public virtual DbSet<BrandingTransactionDesignElement> BrandingTransactionDesignElements { get; set; }
        public virtual DbSet<BrandingTransactionMaterial> BrandingTransactionMaterials { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<DesignElement> DesignElements { get; set; }
        public virtual DbSet<DesignElementPrice> DesignElementPrices { get; set; }
        public virtual DbSet<DigitalFile> DigitalFiles { get; set; }
        public virtual DbSet<DigitalType> DigitalTypes { get; set; }
        public virtual DbSet<DurationType> DurationTypes { get; set; }
        public virtual DbSet<FulfilmentPaymentStatu> FulfilmentPaymentStatus { get; set; }
        public virtual DbSet<FulfilmentProductionPayment> FulfilmentProductionPayments { get; set; }
        public virtual DbSet<FulfilmentScriptingPayment> FulfilmentScriptingPayments { get; set; }
        public virtual DbSet<FulfilmentStatu> FulfilmentStatus { get; set; }
        public virtual DbSet<FulfilmentStatusRule> FulfilmentStatusRules { get; set; }
        public virtual DbSet<MaterialProductionPrice> MaterialProductionPrices { get; set; }
        public virtual DbSet<MaterialScriptingPrice> MaterialScriptingPrices { get; set; }
        public virtual DbSet<MaterialType> MaterialTypes { get; set; }
        public virtual DbSet<MaterialTypeTiming> MaterialTypeTimings { get; set; }
        public virtual DbSet<NewsPaper> NewsPapers { get; set; }
        public virtual DbSet<OnlineDuration> OnlineDurations { get; set; }
        public virtual DbSet<OnlineExtraService> OnlineExtraServices { get; set; }
        public virtual DbSet<OnlineExtraServicePrice> OnlineExtraServicePrices { get; set; }
        public virtual DbSet<OnlinePackagesDurationPrice> OnlinePackagesDurationPrices { get; set; }
        public virtual DbSet<OnlinePlatform> OnlinePlatforms { get; set; }
        public virtual DbSet<OnlinePlatformPrice> OnlinePlatformPrices { get; set; }
        public virtual DbSet<OnlinePurpose> OnlinePurposes { get; set; }
        public virtual DbSet<OnlineTransaction> OnlineTransactions { get; set; }
        public virtual DbSet<OnlineTransactionAiring> OnlineTransactionAirings { get; set; }
        public virtual DbSet<OnlineTransactionAttachment> OnlineTransactionAttachments { get; set; }
        public virtual DbSet<OnlineTransactionExtraService> OnlineTransactionExtraServices { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderFulfilment> OrderFulfilments { get; set; }
        public virtual DbSet<OrderFulfilmentActivity> OrderFulfilmentActivities { get; set; }
        public virtual DbSet<OrderFulfilmentActivityDocument> OrderFulfilmentActivityDocuments { get; set; }
        public virtual DbSet<OrderHistory> OrderHistories { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PrintCategory> PrintCategories { get; set; }
        public virtual DbSet<PrintMediaType> PrintMediaTypes { get; set; }
        public virtual DbSet<PrintProduction> PrintProductions { get; set; }
        public virtual DbSet<PrintServiceColor> PrintServiceColors { get; set; }
        public virtual DbSet<PrintServiceType> PrintServiceTypes { get; set; }
        public virtual DbSet<PrintServiceTypePrice> PrintServiceTypePrices { get; set; }
        public virtual DbSet<PrintTransaction> PrintTransactions { get; set; }
        public virtual DbSet<PrintTransactionAiring> PrintTransactionAirings { get; set; }
        public virtual DbSet<PrintTransactionColor> PrintTransactionColors { get; set; }
        public virtual DbSet<PrintTransactionPublish> PrintTransactionPublishes { get; set; }
        public virtual DbSet<RadioProduction> RadioProductions { get; set; }
        public virtual DbSet<RadioScripterScriptingDetail> RadioScripterScriptingDetails { get; set; }
        public virtual DbSet<RadioScriptingDetail> RadioScriptingDetails { get; set; }
        public virtual DbSet<RadioServicePrice> RadioServicePrices { get; set; }
        public virtual DbSet<RadioStation> RadioStations { get; set; }
        public virtual DbSet<RadioTransaction> RadioTransactions { get; set; }
        public virtual DbSet<RadioTransactionAiring> RadioTransactionAirings { get; set; }
        public virtual DbSet<RadioUserScriptingDetail> RadioUserScriptingDetails { get; set; }
        public virtual DbSet<Scripter> Scripters { get; set; }
        public virtual DbSet<ScriptMaterialQuestion> ScriptMaterialQuestions { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<TimeBelt> TimeBelts { get; set; }
        public virtual DbSet<Timing> Timings { get; set; }
        public virtual DbSet<TransactionStatu> TransactionStatus { get; set; }
        public virtual DbSet<TvScriptingDetail> TvScriptingDetails { get; set; }
        public virtual DbSet<TvServicesPrice> TvServicesPrices { get; set; }
        public virtual DbSet<TVStation> TVStations { get; set; }
        public virtual DbSet<TVTransaction> TVTransactions { get; set; }
        public virtual DbSet<TVTransactionAiring> TVTransactionAirings { get; set; }
        public virtual DbSet<UserActivationCode> UserActivationCodes { get; set; }
        public virtual DbSet<UserAppRole> UserAppRoles { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
    }
}
