//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandingTransactionMaterial
    {
        public int BrandingTransactionMaterialId { get; set; }
        public int BrandingTransactionId { get; set; }
        public int BrandingMaterialId { get; set; }
        public int BrandingMaterialPriceId { get; set; }
        public decimal BrandingMaterialAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
