//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandingTransactionDesignElement
    {
        public int BrandingTransactionDesignElementId { get; set; }
        public int BrandingTransactionId { get; set; }
        public int DesignElementId { get; set; }
        public int DesignElementPriceId { get; set; }
        public decimal DesignElementAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
