//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandingTransaction
    {
        public int BrandingTransactionId { get; set; }
        public int OrderId { get; set; }
        public string OtherColor { get; set; }
        public string AdditionalInformation { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string TransactionStatusCode { get; set; }
        public int UserId { get; set; }
        public string OrderTitle { get; set; }
        public decimal TotalAmount { get; set; }
    }
}
