//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FulfilmentProductionPayment
    {
        public int FulfilmentProductionPaymentId { get; set; }
        public int OrderFulfilmentId { get; set; }
        public string FulfilmentPaymentStatus { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string RefrenceCode { get; set; }
    }
}
