//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialTypeTiming
    {
        public int MaterialTypeTimingId { get; set; }
        public string ServiceTypeCode { get; set; }
        public int MaterialTypeId { get; set; }
        public int TimingId { get; set; }
        public bool IsActive { get; set; }
    }
}
