//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineTransaction
    {
        public int OnlineTransactionId { get; set; }
        public int OrderId { get; set; }
        public int OnlinePurposeId { get; set; }
        public int UserId { get; set; }
        public int OnlinePlatformId { get; set; }
        public int OnlinePlatformPriceId { get; set; }
        public decimal OnlinePlatformAmount { get; set; }
        public string AdditionalInformation { get; set; }
        public bool IsHaveArtWork { get; set; }
        public Nullable<int> ArtWorkPriceId { get; set; }
        public Nullable<decimal> ArtWorkAmount { get; set; }
        public Nullable<int> ArtworkDigitalFileId { get; set; }
        public decimal Price { get; set; }
        public bool IsActive { get; set; }
        public decimal OnlineExtraServiceAmount { get; set; }
        public string OrderTitle { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string TransactionStatusCode { get; set; }
    }
}
