//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineTransactionAttachment
    {
        public int OnlineTransactionAttachmentId { get; set; }
        public int OnlineTransactionId { get; set; }
        public int DigitalFileId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
