//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineTransactionExtraService
    {
        public int OnlineTransactionExtraServiceId { get; set; }
        public int OnlineTransactionId { get; set; }
        public int OnlineExtraServiceId { get; set; }
        public int OnlineExtraServicePriceId { get; set; }
        public decimal OnlineExtraServiceAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
