//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineTransactionAiring
    {
        public int OnlineTransactionAiringId { get; set; }
        public int OnlineTransactionId { get; set; }
        public int OnlineDurationId { get; set; }
        public int OnlinePlatformId { get; set; }
        public decimal Price { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
