//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFulfilmentActivity
    {
        public int OrderFulfilmentActivityId { get; set; }
        public int OrderFulfilmentId { get; set; }
        public string ActvityDescription { get; set; }
        public string FromStatus { get; set; }
        public string ToStatus { get; set; }
        public bool IsSendMail { get; set; }
        public string MailMessage { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsTreated { get; set; }
        public bool IsResponseRequired { get; set; }
    }
}
