//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFulfilment
    {
        public int OrderFulfilmentId { get; set; }
        public int OrderId { get; set; }
        public int ServiceTransactionId { get; set; }
        public string ServiceCode { get; set; }
        public string FulfilmentStatusCode { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
