//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintTransactionAiring
    {
        public int PrintTransactionAiringId { get; set; }
        public int PrintTransactionId { get; set; }
        public int NewsPaperId { get; set; }
        public int PrintColorId { get; set; }
        public int PrintServiceTypePriceId { get; set; }
        public int PrintMediaTypePriceId { get; set; }
        public int NumberOfInserts { get; set; }
        public decimal Price { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
