//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintProduction
    {
        public int PrintProductionId { get; set; }
        public Nullable<int> PrintTransactionId { get; set; }
        public Nullable<int> PrintUserProductionDigitalId { get; set; }
        public Nullable<int> PrintManagerProductionDigitalId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ProductionManagerNote { get; set; }
        public string UserNote { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ProductionManagerId { get; set; }
    }
}
