//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadioServicePrice
    {
        public int Id { get; set; }
        public int RadioId { get; set; }
        public int TimingId { get; set; }
        public int MaterialTypeId { get; set; }
        public decimal Amount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateEffective { get; set; }
        public Nullable<System.DateTime> DateInActive { get; set; }
        public int TimeBeltId { get; set; }
    }
}
