//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadioScripterScriptingDetail
    {
        public int RadioScripterScriptingId { get; set; }
        public Nullable<int> ScripterDigitalFileId { get; set; }
        public string ScripterComment { get; set; }
        public int TransactionId { get; set; }
        public Nullable<int> UserDigitalFileId { get; set; }
        public Nullable<int> ScripterId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserComment { get; set; }
        public bool IsActive { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateApproved { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
