//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadioProduction
    {
        public int RadioProductionId { get; set; }
        public Nullable<int> RadioTransactionId { get; set; }
        public Nullable<int> RadioUserProductionDigitalId { get; set; }
        public Nullable<int> RadioManagerProductionDigitalId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ProductionManagerNote { get; set; }
        public string UserNote { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ProductionManagerId { get; set; }
    }
}
