//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadioTransactionAiring
    {
        public int RadioTransactionAiringId { get; set; }
        public int RadioTransactionId { get; set; }
        public int RadioStationId { get; set; }
        public int MaterialTypeTimingId { get; set; }
        public bool IsActive { get; set; }
        public string DurationTypeCode { get; set; }
        public int Slots { get; set; }
        public int TotalSlots { get; set; }
        public decimal Price { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int TimeBeltId { get; set; }
    }
}
