//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadioTransaction
    {
        public int RadioTransactionId { get; set; }
        public int UserId { get; set; }
        public int OrderId { get; set; }
        public bool IsHaveMaterial { get; set; }
        public int MaterialDigitalFileId { get; set; }
        public string ScriptDescription { get; set; }
        public bool IsHaveApconApproval { get; set; }
        public string ApconApprovalNumber { get; set; }
        public int ApconApprovalTypeId { get; set; }
        public int ApconApprovalTypePriceId { get; set; }
        public decimal ApconApprovalAmount { get; set; }
        public decimal FinalAmount { get; set; }
        public string AiringInstruction { get; set; }
        public string TransactionStatusCode { get; set; }
        public int ScriptDigitalFileId { get; set; }
        public string OrderTitle { get; set; }
        public int MaterialTypeId { get; set; }
        public int MaterialProductionPriceId { get; set; }
        public decimal ProductionAmount { get; set; }
        public int MaterialScriptingPriceId { get; set; }
        public decimal ScriptingAmount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ScriptMaterialQuestionCode { get; set; }
    }
}
