//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVTransactionProduction
    {
        public int TVTransactionScriptingId { get; set; }
        public int TVTransactionId { get; set; }
        public int MaterialTypeId { get; set; }
        public int MaterialProductionPriceId { get; set; }
        public decimal ProductionAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
