//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivationCode
    {
        public int UserActivationCodeId { get; set; }
        public int RegistrationId { get; set; }
        public string ActivationCode { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public bool IsUsed { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
