//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADit.Domain.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Choose an Option].
        /// </summary>
        public static string ChooseOption {
            get {
                return ResourceManager.GetString("ChooseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Tv Station].
        /// </summary>
        public static string GetTvStationText {
            get {
                return ResourceManager.GetString("GetTvStationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Advert Duration].
        /// </summary>
        public static string SelectAdvertDuration {
            get {
                return ResourceManager.GetString("SelectAdvertDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Approval Type].
        /// </summary>
        public static string SelectApprovalTypeText {
            get {
                return ResourceManager.GetString("SelectApprovalTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Branding Material].
        /// </summary>
        public static string SelectBrandingMaterialText {
            get {
                return ResourceManager.GetString("SelectBrandingMaterialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Color].
        /// </summary>
        public static string SelectColorText {
            get {
                return ResourceManager.GetString("SelectColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Contact].
        /// </summary>
        public static string SelectContact {
            get {
                return ResourceManager.GetString("SelectContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Design Element].
        /// </summary>
        public static string SelectDesignElementText {
            get {
                return ResourceManager.GetString("SelectDesignElementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Choose Newspaper].
        /// </summary>
        public static string SelectDropDownNewsPaperText {
            get {
                return ResourceManager.GetString("SelectDropDownNewsPaperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select your Print Category].
        /// </summary>
        public static string SelectDropDownPrintCategoryText {
            get {
                return ResourceManager.GetString("SelectDropDownPrintCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Choose your Service type].
        /// </summary>
        public static string SelectDropDownServiceTypeText {
            get {
                return ResourceManager.GetString("SelectDropDownServiceTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Print media Type].
        /// </summary>
        public static string SelectePrintMediaType {
            get {
                return ResourceManager.GetString("SelectePrintMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Tv Station].
        /// </summary>
        public static string SelecteTVStation {
            get {
                return ResourceManager.GetString("SelecteTVStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select One Option].
        /// </summary>
        public static string SelectMaterialQuestion {
            get {
                return ResourceManager.GetString("SelectMaterialQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Material Type].
        /// </summary>
        public static string SelectMaterialType {
            get {
                return ResourceManager.GetString("SelectMaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Material Type Timing].
        /// </summary>
        public static string SelectMaterialTypeTimingText {
            get {
                return ResourceManager.GetString("SelectMaterialTypeTimingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SelectArtworkPrice].
        /// </summary>
        public static string SelectOnlineArtworktext {
            get {
                return ResourceManager.GetString("SelectOnlineArtworktext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Online Extra Service].
        /// </summary>
        public static string SelectOnlineExraServicesText {
            get {
                return ResourceManager.GetString("SelectOnlineExraServicesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Online Platform].
        /// </summary>
        public static string SelectOnlinePlatformText {
            get {
                return ResourceManager.GetString("SelectOnlinePlatformText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Online Purpose].
        /// </summary>
        public static string SelectOnlinePurposeText {
            get {
                return ResourceManager.GetString("SelectOnlinePurposeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Order Status].
        /// </summary>
        public static string SelectOrderStatus {
            get {
                return ResourceManager.GetString("SelectOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Print Service Color].
        /// </summary>
        public static string SelectPrintServiceColor {
            get {
                return ResourceManager.GetString("SelectPrintServiceColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Radio Station].
        /// </summary>
        public static string SelectRadioStation {
            get {
                return ResourceManager.GetString("SelectRadioStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Timing Belt].
        /// </summary>
        public static string SelectTimingBelt {
            get {
                return ResourceManager.GetString("SelectTimingBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Timing].
        /// </summary>
        public static string SelectTimingText {
            get {
                return ResourceManager.GetString("SelectTimingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select  User Roles].
        /// </summary>
        public static string SelectUserRoles {
            get {
                return ResourceManager.GetString("SelectUserRoles", resourceCulture);
            }
        }
    }
}
