//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADit.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADit.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apcon Approval Type Already Exist.
        /// </summary>
        public static string ApconExist {
            get {
                return ResourceManager.GetString("ApconExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding.
        /// </summary>
        public static string Branding {
            get {
                return ResourceManager.GetString("Branding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Type already exist.
        /// </summary>
        public static string ColorExist {
            get {
                return ResourceManager.GetString("ColorExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email to confirm your registration.
        /// </summary>
        public static string ConfirmRegistrationText {
            get {
                return ResourceManager.GetString("ConfirmRegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name already existed ,Please use another name.
        /// </summary>
        public static string DescriptionExist {
            get {
                return ResourceManager.GetString("DescriptionExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Element already exist.
        /// </summary>
        public static string DesignExist {
            get {
                return ResourceManager.GetString("DesignExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Type already exist.
        /// </summary>
        public static string DurationExist {
            get {
                return ResourceManager.GetString("DurationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already used for registration..
        /// </summary>
        public static string EmailAlreadyUsedText {
            get {
                return ResourceManager.GetString("EmailAlreadyUsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGradeExist.
        /// </summary>
        public static string GradeExist {
            get {
                return ResourceManager.GetString("GradeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or password provided is incorrect .
        /// </summary>
        public static string IncorrectPasswordText {
            get {
                return ResourceManager.GetString("IncorrectPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string IsActiveForNewItem {
            get {
                return ResourceManager.GetString("IsActiveForNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string IsActiveToDelete {
            get {
                return ResourceManager.GetString("IsActiveToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type already exist.
        /// </summary>
        public static string MaterialTypeExist {
            get {
                return ResourceManager.GetString("MaterialTypeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Duration Description Already Exist.
        /// </summary>
        public static string OnlineDurationAlreadyExist {
            get {
                return ResourceManager.GetString("OnlineDurationAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Category Exist.
        /// </summary>
        public static string PrintCateoryExist {
            get {
                return ResourceManager.GetString("PrintCateoryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Service Type Exist.
        /// </summary>
        public static string PrintServiceTypeExist {
            get {
                return ResourceManager.GetString("PrintServiceTypeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Station Already Existed.
        /// </summary>
        public static string RadioStationExist {
            get {
                return ResourceManager.GetString("RadioStationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Radio Station Exist.
        /// </summary>
        public static string RadioStationExists {
            get {
                return ResourceManager.GetString("RadioStationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must Select An Option.
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already added the service.
        /// </summary>
        public static string ServiceExist {
            get {
                return ResourceManager.GetString("ServiceExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing already exist.
        /// </summary>
        public static string TimingExist {
            get {
                return ResourceManager.GetString("TimingExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Television Station Already Exist.
        /// </summary>
        public static string TvStationExist {
            get {
                return ResourceManager.GetString("TvStationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already used for registration, please provide another email address.
        /// </summary>
        public static string UserAlreadyExistText {
            get {
                return ResourceManager.GetString("UserAlreadyExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserNameWatermarkMessage {
            get {
                return ResourceManager.GetString("UserNameWatermarkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user have already been assingned to this role.
        /// </summary>
        public static string UserRolesExist {
            get {
                return ResourceManager.GetString("UserRolesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already registered but you need to validate your account, Check your email for the verification Link .
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
    }
}
